### ISSUE TITLE
Unable to login to Dashboard

### ISSUE THREAD

**Issue by ptechpro** [seriohub/velero-ui#28]
Unable to login to the dashboard and trying with default creds (admin/admin)
Please refer the attached screenshot and guide if I am missing anything.

**Comment by davideserio** [comment]
Hi,
Did you install via helm?
Can you attach the diagnostic info on the login page? Please remove any sensitive information

**Comment by ptechpro** [comment]
Hi,

Yes. I used helm for installation. I am trying to attach the screenshot but for somereason I am not able to..However, I have copied the info from the login page as below. Only the Get UI and API URL fields shows as 'Green'. and When I provide the creds and click on login, nothing happens, no errors pops up. 

Diagnostic:

Get UI URL: http://x.x.x.x:30002
Get API URL: http://:30001/api
Check API reachable
Get API architecture:
Get Origins:
Validate ORIGINS ERROR: ORIGINS must contain http://x.x.x.x:30002 If you have problems you can try to use *
Check Watchdog
Cluster Online: false
Nodes:
Nodes in error:

**Comment by davideserio** [comment]
Can you share the values-override.yaml file? (Please remove any sensitive information)

**Comment by ptechpro** [comment]
Here it is...I havnt uncommented the ones which think not mandate.

#
# Global
#
global:
  veleroNamespace: velero
  # kubernetesClusterDomain: my-cluster

#
# API Config
#
apiConfig:
  #
  awsAccessKeyId: xxxxxxxxxxxxx  
  awsSecretAccessKey: xxxxxxxxxxxxxxxxxxxx
  # debugLevel: debug
  veleroCliVersion: v1.13.0
  # apiTokenExpirationMin: "30"
  # apiTokenRefreshExpirationDays: "7"
  storage:
    enabled: true
    storageClassName: xxx-xxx-xxxx

#
# You can use nodeport or ingress according to your needs
#
#
# Nodeport
#
uiNp:
  enabled: true
  #ip: "10.10.0.100"  # any ip address of your cluster
  apiPort: "30001"
  uiPort: "30002"
#
# Ingress
#
uiIngress:
  enabled: false
  # ingressClassName: nginx
  # metadata:
  #   annotations:
  #     cert-manager.io/cluster-issuer: "letsencrypt-prod" 
  spec:
    tls:
  #  - hosts:
  #    - velero.<your-domain>
  #    secretName: velero-ui-tls

#
# Watchdog Cron
#
report:
  schedule: 0 8 * * *

#
# Watchdog Daemon
#
watchdogConfig:
  # config
  k8SInclusterMode: "True"
  # k8sVeleroNamespace: "velero"
  processClusterName:  test-cluster
  # processCycleSec: 300
  # expiresDaysWarning: 29
  notificationSkipCompleted: "False"
  # notificationSkipInProgress: "True"
  # notificationSkipRemoved: "True"
  # notificationSkipDeleting: "True"
   
  # email
  emailEnable: "False"
  emailAccount: <your-email>
  emailPassword: <your-password>
  emailRecipients: <email-recipents-comma-saparted>
  emailSmtpPort: <smtp-port>
  emailSmtpServer: <smtp-server>
  
  # slack
  slackEnable: "False"
  slackChannel: <channel-id>  
  slackToken: <token>
  
  # telegram
  telegramEnable: "False"
  telegramChatId: "<telegram-chat-id>"
  telegramToken: "<telegram-token>"

**Comment by ptechpro** [comment]
#
# Global
#
global:
  veleroNamespace: velero
  # kubernetesClusterDomain: my-cluster
#
# API Config
#
apiConfig:
  #
  awsAccessKeyId: xxxxxxxxxxxxx  
  awsSecretAccessKey: xxxxxxxxxxxxxxxxxxxx
  # debugLevel: debug
  veleroCliVersion: v1.13.0
  # apiTokenExpirationMin: "30"
  # apiTokenRefreshExpirationDays: "7"
  storage:
    enabled: true
    storageClassName: xxx-xxx-xxxx
#
# You can use nodeport or ingress according to your needs
#
#
# Nodeport
#
uiNp:
  enabled: true
  #ip: "10.10.0.100"  # any ip address of your cluster
  apiPort: "30001"
  uiPort: "30002"
#
# Ingress
#
uiIngress:
  enabled: false
  # ingressClassName: nginx
  # metadata:
  #   annotations:
  #     cert-manager.io/cluster-issuer: "letsencrypt-prod" 
  spec:
    tls:
  #  - hosts:
  #    - velero.<your-domain>
  #    secretName: velero-ui-tls
#
# Watchdog Cron
#
report:
  schedule: 0 8 * * *
#
# Watchdog Daemon
#
watchdogConfig:
  # config
  k8SInclusterMode: "True"
  # k8sVeleroNamespace: "velero"
  processClusterName: test-cluster
  # processCycleSec: 300
  # expiresDaysWarning: 29
  notificationSkipCompleted: "False"
  # notificationSkipInProgress: "True"
  # notificationSkipRemoved: "True"
  # notificationSkipDeleting: "True"
   
  # email
  emailEnable: "False"
  emailAccount: <your-email>
  emailPassword: <your-password>
  emailRecipients: <email-recipents-comma-saparted>
  emailSmtpPort: <smtp-port>
  emailSmtpServer: <smtp-server>
  
  # slack
  slackEnable: "False"
  slackChannel: <channel-id>
  slackToken: <token>
  
  # telegram
  telegramEnable: "False"
  telegramChatId: "<telegram-chat-id>"
  telegramToken: "<telegram-token>"

**Comment by ptechpro** [comment]
`#
# Global
#
global:
  veleroNamespace: velero
  # kubernetesClusterDomain: my-cluster
#
# API Config
#
apiConfig:
  #
  awsAccessKeyId: xxxxxxxxxxxxx  
  awsSecretAccessKey: xxxxxxxxxxxxxxxxxxxx
  # debugLevel: debug
  veleroCliVersion: v1.13.0
  # apiTokenExpirationMin: "30"
  # apiTokenRefreshExpirationDays: "7"
  storage:
    enabled: true
    storageClassName: xxx-xxx-xxxx
#
# You can use nodeport or ingress according to your needs
#
#
# Nodeport
#
uiNp:
  enabled: true
  #ip: "10.10.0.100"  # any ip address of your cluster
  apiPort: "30001"
  uiPort: "30002"
#
# Ingress
#
uiIngress:
  enabled: false
  # ingressClassName: nginx
  # metadata:
  #   annotations:
  #     cert-manager.io/cluster-issuer: "letsencrypt-prod" 
  spec:
    tls:
  #  - hosts:
  #    - velero.<your-domain>
  #    secretName: velero-ui-tls
#
# Watchdog Cron
#
report:
  schedule: 0 8 * * *
#
# Watchdog Daemon
#
watchdogConfig:
  # config
  k8SInclusterMode: "True"
  # k8sVeleroNamespace: "velero"
  processClusterName: test-cluster
  # processCycleSec: 300
  # expiresDaysWarning: 29
  notificationSkipCompleted: "False"
  # notificationSkipInProgress: "True"
  # notificationSkipRemoved: "True"
  # notificationSkipDeleting: "True"
   
  # email
  emailEnable: "False"
  emailAccount: <your-email>
  emailPassword: <your-password>
  emailRecipients: <email-recipents-comma-saparted>
  emailSmtpPort: <smtp-port>
  emailSmtpServer: <smtp-server>
  
  # slack
  slackEnable: "False"
  slackChannel: <channel-id>
  slackToken: <token>
  
  # telegram
  telegramEnable: "False"
  telegramChatId: "<telegram-chat-id>"
  telegramToken: "<telegram-token>"`

**Comment by ptechpro** [comment]
Please find the below. Havnt configued few things like ingress, watchdog config etcx
# Global
#
global:
  veleroNamespace: velero
  # kubernetesClusterDomain: my-cluster
#
# API Config
#
apiConfig:
  #
  awsAccessKeyId: xxxxxxxxxxxxx  
  awsSecretAccessKey: xxxxxxxxxxxxxxxxxxxx
  # debugLevel: debug
  veleroCliVersion: v1.13.0
  # apiTokenExpirationMin: "30"
  # apiTokenRefreshExpirationDays: "7"
  storage:
    enabled: true
    storageClassName: xxx-xxx-xxxx
#
# You can use nodeport or ingress according to your needs
#
#
# Nodeport
#
uiNp:
  enabled: true
  #ip: "10.10.0.100"  # any ip address of your cluster
  apiPort: "30001"
  uiPort: "30002"
#
# Ingress
#
uiIngress:
  enabled: false
  # ingressClassName: nginx
  # metadata:
  #   annotations:
  #     cert-manager.io/cluster-issuer: "letsencrypt-prod" 
  spec:
    tls:
  #  - hosts:
  #    - velero.<your-domain>
  #    secretName: velero-ui-tls

**Comment by davideserio** [comment]
Hi,
try uncommenting and set uiNp.ip

**Comment by ptechpro** [comment]
Great. That was the problem with the node port IP. It works now! Thank you very much
