### ISSUE TITLE
Return to login page again

### ISSUE THREAD

**Issue by mmahvari** [seriohub/velero-ui#40]
Hello,

I installed velero-ui via helm. After enter admin/admin for login, return to login page again. And after that when I go to http://192.68.10.10/dashboard show dashboard page and immediately go to login page again.

I get websocket is closed before the connection is established error when I inspect the login page.

best regards

**Comment by davideserio** [comment]
https://github.com/seriohub/velero-ui/issues/38#issuecomment-2269430545

Let me know if that solves the problem

**Comment by mmahvari** [comment]
It works now! Thank you very much.
