### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by leandrok** [seriohub/velero-ui#42]
Hello! This is a very promising project, congratulations.

I have deployed velero-ui using the Helm Chart. Our Kubernetes clusters only uses ARM. This is the result:

```
$ kubectl get pod -n velero --context=infra
NAME                                         READY   STATUS    RESTARTS      AGE
infra-velero-77c84b7b98-vjtqp                1/1     Running   0             44m
infra-velero-vui-api-7ff9d4c44-l8kch         1/1     Running   0             48s
infra-velero-vui-ui-74776c4bc8-jvz8h         0/1     Error     3 (29s ago)   48s
infra-velero-vui-watchdog-7895b8cdd7-7fxtv   1/1     Running   0             48s
```

As you can see both api and watchdog services are able to start without any issues. But the UI pod is failing with this error:

```
kubectl logs infra-velero-vui-ui-74776c4bc8-jvz8h -n velero --context=infra
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

This occurs because the docker image was not built to support ARM. I confirmed that the other docker repos are building the images with ARM support already (example: https://hub.docker.com/r/dserio83/velero-api).

Can you also build the velero-ui image with ARM support please? (https://hub.docker.com/r/dserio83/velero-ui)

Thank you very much in advance!

**Comment by davideserio** [comment]
I have built the Velero-UI for ARM. Although I don't have the capability to test the image in a cluster that uses ARM, I believe there shouldn't be any issues. Please let me know if the system runs smoothly.

**Comment by leandrok** [comment]
Thanks a lot! I'm using the new image (dserio83/velero-ui:0.1.16) and the pod is running like a charm.

But I can't confirm if everything works correctly yet. Although I can see the login page, once I enter the username and the password and I click the "Login" button, nothing occurs. I don't see any errors in the pods either:

```
$ kubectl logs infra-velero-vui-ui-74776c4bc8-zzw2g -n velero --context=infra

   ▲ Next.js 14.1.2
   - Local:        http://localhost:3000
   - Network:      http://0.0.0.0:3000

 ✓ Ready in 91ms
```

I tried changing the default password but didn't work. By the way, since I'm testing this service, for now I'm just using port-forwarding to access the service:

```
$ kubectl port-forward service/infra-velero-vui-ui-np -n velero 8080:80 --context=infra
```

And then opening the UI using http://localhost:8080. Not sure if this information is relevant.

Do you think this could be related to the ARM image? I mean, maybe some library used by the application is not supporting ARM?

Thanks again!
