### ISSUE TITLE
dashboard login not working

### ISSUE THREAD

**Issue by yyardeng** [seriohub/velero-ui#49]
i have installed the latest helm chart for vui. when logging in with the default admin credentials, the dashboard redirects back to the login page. it briefly shows the checks in error state but when it redirects back to login all diagnostic checks show as green again.

i have tried the solutions mentioned in similar issues but they did not work.

the screen before it redirects back to login:

![image](https://github.com/user-attachments/assets/13c697ed-7b35-4b20-a882-5727e2c85484)

diagnostics:

# Agent State Manager Report**

- Backend info
  - app_name: **velero-api**;
  - helm_app_version: **0.1.15**;
  - helm_version: **0.1.17**;
  - helm_api: **0.1.18**;
  - helm_ui: **0.1.17**;
  - api_release_version: **0.1.18**;
  - helm_watchdog: **0.1.6**;
- UI URL: **https://###.###.###**
- API URL: **https://###.###.###/api**
- K8s Health
  - cluster online: **true**
  - nodes:
    - total: **6**;
    - in error: **0**;
- API Origins
  - https://www.custom.velero.domain;
- Architecture: **amd64**
- Watchdog: **alive**
- Compatibility: **true**
- Boolean State
  - getUiURL: **true**;
  - getApiURL: **true**;
  - checkApiReacheable: **true**;
  - getArchitecture: **true**;
  - getOrigins: **true**;
  - validateOrigins: **true**;
  - getWatchdogInfo: **true**;
  - getClusterHealth: **true**;
  - getUiApiVerCompatibility: **true**;
 
**velero-ui-config cm:**

  NEXT_PUBLIC_REFRESH_DATATABLE_AFTER: "1500"
  NEXT_PUBLIC_REFRESH_RECENT: "5000"
  NEXT_PUBLIC_VELERO_API_NAME: k8scluster
  NEXT_PUBLIC_VELERO_API_NAME_1: k8scluster
  NEXT_PUBLIC_VELERO_API_URL: https://www.custom.velero.domain/api
  NEXT_PUBLIC_VELERO_API_URL_1: https://www.custom.velero.domain/api
  NEXT_PUBLIC_VELERO_API_WS: wss://www.custom.velero.domain
  NEXT_PUBLIC_VELERO_API_WS_1: wss://www.custom.velero.domain

**velero-api-config cm:**

  API_ENABLE_DOCUMENTATION: "1"
  API_ENDPOINT_PORT: "8001"
  API_ENDPOINT_URL: 0.0.0.0
  API_RATE_LIMITER_CUSTOM_1: Security:xxx:60:20
  API_RATE_LIMITER_L1: "60:20"
  API_TOKEN_EXPIRATION_MIN: "60"
  API_TOKEN_REFRESH_EXPIRATION_DAYS: "7"
  DEBUG_LEVEL: info
  DOWNLOAD_TMP_FOLDER: /tmp/velero-api
  K8S_IN_CLUSTER_MODE: "True"
  K8S_VELERO_NAMESPACE: velero
  K8S_VELERO_UI_NAMESPACE: velero
  ORIGINS_1: https://custom.velero.domain
  REPORT_CRONJOB_NAME: velero-ui-report
  SECURITY_DISABLE_USERS_PWD_RATE: "1"
  SECURITY_PATH_DATABASE: ./data
  VELERO_CLI_DEST_PATH: /usr/local/bin
  VELERO_CLI_PATH: ./velero-client
  VELERO_CLI_PATH_CUSTOM: ./velero-client-binary
  VELERO_CLI_VERSION: v1.12.2
  VELERO_WATCHDOG_PORT: "8001"
  VELERO_WATCHDOG_URL: velero-ui-watchdog-clusterip

**securityTokenKey** is provided in the helm values and is included in the velero secret data under **SECURITY_TOKEN_KEY**.

accessing /api/docs works.
i can authorize in the swagger UI, but sending requests to endpoints that require authorization does not work, for example /v1/backup/get

![image](https://github.com/user-attachments/assets/e7060d60-8fc0-4d50-ac5d-bf12bced6b48)

![image](https://github.com/user-attachments/assets/a8fea466-cf2b-43cd-ae90-647269901148)

**Comment by davideserio** [comment]
Can you check the logs in API pod and report any errors?

**Comment by rrademak** [comment]
Have the exact same issue and no workaround to bypass it. The logging does not show any error 
All is green:
![image](https://github.com/user-attachments/assets/2ae9754e-9d56-4861-b452-0865226d15c0)

**Comment by rrademak** [comment]
mines fixed seems to be the SECURITY_TOKEN_KEY
