### ISSUE TITLE
UI Login Credentials

### ISSUE THREAD

**Issue by saeed-didar** [seriohub/velero-ui#50]
Hi, I'm so glad I found this great project, I'm having trouble logging in to the homepage! That is, what exactly is the username and password to log in through the ui? I enter "admin" "admin" from the documentation, but it doesn't accept! Thanks for any advice.

**Comment by davideserio** [comment]
It seems like you're having trouble logging in to the UI.
Please check Point 3 in the [Troubleshooting Guide](https://vui.seriohub.com/docs/troubleshooting). 
It provides steps for resolving login issues.
Let me know if you need further assistance.
