### ISSUE TITLE
API is not proxied through the UI

### ISSUE THREAD

**Issue by onigoetz** [seriohub/velero-ui#53]
Hi,
I'm trying your UI via the helm chart but I see that in the ingress, the API and UI are both referenced in the ingress, which means that it's not possible to use the UI with port-forwarding without an ingress.

In the architecture diagram on this page: https://vui.seriohub.com/docs/getting-started/software-architecture/single-cluster it is explained that the API is accessed through the UI but that's actually not the case.

I don't have a custom domain so can't actually try this tool and would also be interested in #44

I would be happy to propose a PR so that the API actually goes through the UI, would you merge such a PR?

**Comment by davideserio** [comment]
Here are some points to address your issue:

Port-Forwarding Without an Ingress
If you're unable to use an ingress, you can still access the UI and API by using a [NodePort](https://github.com/seriohub/velero-helm/blob/98cbe4618b6d9257d18b0ea242333e0301a1a342/values-override.yaml#L33) service configuration. This will allow you to bypass the need for an ingress.
Try using NodePort and let me know if you encounter any further issues.

Architecture and API Access via UI
The application consists of a UI that needs to communicate with the API service. Therefore, the API must have endpoints accessible from the client's browser. For this purpose, the Helm chart is configured to support installation via ingress or NodePort to expose both the UI and the API.
If neither NodePort nor ingress fully meets your requirements, we encourage you to modify the configuration to better fit your setup. Additionally, your proposal to route the API through the UI would align well with some deployment scenarios but represents a slightly different architecture from the current approach.
On this note, I will update the documentation images as soon as possible.

Enhancements and Contributions
As an open-source project, we actively focus on delivering new features and addressing critical issues. While we aim to accommodate various use cases, it’s not always feasible to develop enhancements that cover every possible scenario.
That said, issues labeled as enhancement are always welcomed and represent valuable improvements. Although we may not be able to implement all of them immediately, we leave them open in the hope of dedicating time to them in the future or referring them to other contributors.

We value every contribution and encourage anyone who wants to contribute to the project to go ahead with a PR. If you have any further questions or need clarification, feel free to ask!

**Comment by onigoetz** [comment]
> If you're unable to use an ingress, you can still access the UI and API by using a [NodePort](https://github.com/seriohub/velero-helm/blob/98cbe4618b6d9257d18b0ea242333e0301a1a342/values-override.yaml#L33) service configuration (you need to [disable ingress](https://github.com/seriohub/velero-helm/blob/98cbe4618b6d9257d18b0ea242333e0301a1a342/values-override.yaml#L42) if you are using nodeport ). This will allow you to bypass the need for an ingress.
> Try using NodePort and let me know if you encounter any further issues.

I did try the NodePort, but it didn't work for me.
But the cause might have been that the helm chart used an older version of the API and UI docker images. I took the long route to setup a domain with an ingress but my initial issue remained (when logging in, I would see a glimpse of the dashboard and get thrown back to the login screen), and an update of the docker images fixed that.

> Additionally, your proposal to route the API through the UI would align well with some deployment scenarios but represents a slightly different architecture from the current approach.

I  understand, by the way, how do you plan to make it work for multi-cluster deployments ?

**Comment by davideserio** [comment]
Currently, the multi-cluster system operates as follows: the core component acts as a gateway, enabling a unified [dashboard](https://vui.seriohub.com/docs/guide/features/core) to display the backup status of all connected clusters. Additionally, it allows operations to be performed on each individual cluster independently.

The VUI-API functions as an agent and must be deployed on every cluster that needs to be monitored, while the VUI-CORE and VUI-UI components are deployed only once, centrally. Communication between the core and the agents is required for the system to function correctly.

We are also developing some features to enable cross-cluster operations.
